const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
const storage=new Map();
const refs=[],effects=[],listeners={};let callback,now=0;
const jsx=(type,props)=>({type,props});
const moduleObject={exports:{}};
const skillsModule={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/skills.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{module:skillsModule,exports:skillsModule.exports});
const loreModule={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/lore.tsx','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{module:loreModule,exports:loreModule.exports,require:()=>({jsx,jsxs:jsx})});
const equipmentModule={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/equipment.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{module:equipmentModule,exports:equipmentModule.exports});
const sandbox={localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},exports:moduleObject.exports,module:moduleObject,require:(name)=>name==='./lore'?loreModule.exports:name==='./skills'?skillsModule.exports:name==='./equipment'?equipmentModule.exports:name==='react'?{useRef:v=>{const r={current:v};refs.push(r);return r;},useState:v=>[v,()=>{}],useEffect:f=>effects.push(f)}:name==='react/jsx-runtime'?{jsx,jsxs:jsx}:new Proxy({},{get:()=>()=>null}),performance:{now:()=>now},requestAnimationFrame:f=>{callback=f;return 1;},cancelAnimationFrame:()=>{},window:{addEventListener:(n,f)=>listeners[n]=f,removeEventListener:()=>{}},document:{addEventListener:()=>{},removeEventListener:()=>{}},console,Set,Map,Math};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/page.tsx','utf8').replace(' return <main>', ' globalThis.testApi={buy,progress,equipWeapon,buyAdvanced,collectPower,takeHit,swing,gearAction,throwShield,lunge,damage,equipment,buySkill,skill,recoverRelic,itemAction,hasItem}; return <main>'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,sandbox);
const tree=moduleObject.exports.default();effects.forEach(f=>f());
function find(node,predicate){if(!node)return; if(Array.isArray(node)){for(const n of node){const r=find(n,predicate);if(r)return r;}}else if(typeof node==='object'){if(predicate(node))return node;return find(node.props?.children,predicate);}}
const begin=find(tree,n=>n.props?.className==='primary');const g=refs[1].current,inputs=refs[2].current;
function advance(seconds){for(let i=0;i<seconds*100;i++){now+=10;callback(now);}}
function reset(){begin.props.onClick();}
reset();advance(18);assert.equal(g.mode,'lost','Doing nothing eventually loses');assert.equal(g.hp,0);
reset();assert.equal(g.hp,5);assert.equal(g.enemies.length,0);assert.equal(g.time,0);
g.enemies.push({x:200,y:465,hp:3,wind:-1,flash:0,kind:'grunt',maxHp:3,speed:65,warning:.8});listeners.keydown({code:'Space',preventDefault(){},repeat:false});advance(.08);listeners.keyup({code:'Space'});assert.equal(g.enemies[0].hp,1,'Tap deals sword damage');assert.equal(g.bolts.length,0,'Tap does not cast');
reset();listeners.keydown({code:'Space',preventDefault(){},repeat:false});advance(.3);assert.ok(g.bolts.length>0,'Hold shoots');assert.equal(g.slash,0,'Hold does not swing');listeners.keyup({code:'Space'});
reset();g.enemies.push({x:200,y:471,hp:3,wind:.05,flash:0,kind:'grunt',maxHp:3,speed:65,warning:.8});inputs.left.add(1);advance(.1);assert.equal(g.hp,5);assert.equal(g.blocks,1,'Shield blocks');advance(5);assert.equal(g.broken,true);inputs.left.clear();advance(2);assert.equal(g.broken,false,'Release recovers exhausted shield');
reset();g.time=90;advance(.01);assert.equal(g.mode,'playing','No time limit');
reset();const kinds=new Set();let cleared=0;
for(let i=0;i<30000&&g.wave<7;i++){for(const e of g.enemies){kinds.add(e.kind);e.hp=0;}advance(.01);cleared=Math.max(cleared,g.wave-1);}
assert.equal(g.wave,7,'Waves continue beyond first boss');assert.equal(g.mode,'playing');assert.equal(kinds.size,5,'All five enemy types spawned');assert.ok(g.coins>100,'Kills and wave rewards credited');
reset();g.wave=5;g.remaining=1;g.spawn=0;advance(.01);assert.equal(g.enemies[0].kind,'boss');assert.ok(g.enemies[0].hp>28);
g.enemies[0].y=471;g.enemies[0].wind=.01;advance(.02);assert.equal(g.hp,3,'Boss hits for two health');g.enemies[0].hp=0;advance(.01);assert.equal(g.hp,4,'Boss clear heals one');assert.ok(g.rest>0);const coins=g.coins;advance(1);assert.equal(g.coins,coins,'Wave reward only awarded once');
reset();assert.equal(g.wave,1);assert.equal(g.coins,0);assert.equal(g.remaining,4);
reset();advance(2);listeners.blur();const pausedTime=g.time;advance(2);assert.equal(g.mode,'paused');assert.equal(g.time,pausedTime,'Pause freezes simulation');assert.equal(inputs.right.size,0);
console.log('PASS: idle defeat, restart, sword tap, magic hold, blocking, exhaustion/recovery, endless waves, enemy variety, boss damage/rewards, reset, pause.');



reset();g.enemies.push({x:200,y:100,hp:0,kind:'boss',maxHp:30,speed:42,warning:1.1,wind:-1,flash:0});advance(.01);
assert.equal(g.coins,0,'Enemy coins wait on the road');assert.equal(g.loot.reduce((n,c)=>n+c.value,0),50,'Boss drops full reward');const lootBefore=JSON.stringify(g.loot);g.mode='paused';advance(1);assert.equal(JSON.stringify(g.loot),lootBefore,'Pause freezes coin physics');g.mode='playing';advance(3);assert.equal(g.loot.length,0,'Approaching hero collects every coin');assert.equal(g.coins,50);assert.ok(JSON.parse(storage.get('runeblade-progress-v1')).coins>=50,'Collected earnings persist immediately');const collectedCoins=g.coins;advance(.2);assert.equal(g.coins,collectedCoins,'Pickups cannot pay twice');
g.mode='lost';const api=sandbox.testApi;api.progress.current={coins:200,sword:0,magic:0,shield:0};api.buy('sword');assert.equal(api.progress.current.coins,180);assert.equal(api.progress.current.sword,1);assert.equal(JSON.parse(storage.get('runeblade-progress-v1')).sword,1);
reset();g.enemies.push({x:200,y:465,hp:5,kind:'grunt',maxHp:5,speed:65,warning:.8,wind:-1,flash:0});listeners.keydown({code:'Space',preventDefault(){},repeat:false});advance(.08);listeners.keyup({code:'Space'});assert.equal(g.enemies[0].hp,2.5,'Sword upgrade affects real combat');
api.buy('magic');assert.equal(api.progress.current.magic,0,'No purchases during a run');g.mode='lost';api.progress.current={coins:0,sword:0,magic:0,shield:0};api.buy('magic');assert.equal(api.progress.current.magic,0,'Cannot overspend');api.progress.current={coins:100,sword:30,magic:0,shield:0};api.buy('sword');assert.equal(api.progress.current.coins,100,'Max rank cannot be purchased again');
console.log('PASS: immediate coin persistence, purchase cost, saved ranks, combat benefit, purchase guards.');

g.mode='lost';api.progress.current={coins:600,sword:1,magic:0,shield:0};api.equipWeapon(2);assert.equal(api.progress.current.coins,600,'Cannot skip unlock order');api.equipWeapon(1);assert.equal(api.progress.current.coins,460);assert.equal(api.progress.current.equipped,1);api.equipWeapon(0);api.equipWeapon(1);assert.equal(api.progress.current.coins,460,'Re-equipping is free');api.equipWeapon(2);assert.equal(api.progress.current.coins,100);assert.equal(JSON.parse(storage.get('runeblade-progress-v1')).equipped,2);
reset();g.enemies.push({x:200,y:465,hp:10,kind:'grunt',maxHp:10,speed:65,warning:.8,wind:-1,flash:0});listeners.keydown({code:'Space',preventDefault(){},repeat:false});advance(.08);listeners.keyup({code:'Space'});assert.equal(g.enemies[0].hp,5,'Runic sword stacks with mastery');api.equipWeapon(0);assert.equal(api.progress.current.equipped,2,'Cannot switch during combat');
console.log('PASS: weapon unlock order, costs, free equip, persisted selection, combat damage and mid-run guard.');
reset();g.remaining=0;g.enemies=[{x:200,y:280,hp:5,kind:'archer',maxHp:5,speed:65,warning:.8,wind:-1,flash:0}];advance(.85);assert.equal(g.hostile.length,1,'Archer fires after warning');assert.equal(g.hp,5,'Projectile has travel time');inputs.left.add(1);advance(1.2);assert.equal(g.hp,5,'Shield blocks projectile');assert.ok(g.blocks>0);
reset();g.remaining=0;g.hostile=[{x:200,y:500,vx:0,vy:200}];advance(.04);assert.equal(g.hp,4,'Unblocked projectile hurts');assert.equal(g.hostile.length,0,'Projectile consumed once');
reset();g.remaining=0;g.hostile=[{x:200,y:280,vx:0,vy:200}];advance(.1);assert.equal(g.rest,0,'Wave cannot clear with projectile in flight');listeners.blur();const shotY=g.hostile[0].y;advance(2);assert.equal(g.hostile[0].y,shotY,'Pause freezes projectiles');
reset();g.remaining=0;g.enemies=[{x:200,y:280,hp:40,kind:'boss',maxHp:40,speed:42,warning:1.1,wind:-1,flash:0}];advance(1.15);assert.equal(g.hostile.length,3,'Boss fires three-projectile volley');assert.equal(g.enemies[0].casts,1);const bossY=g.enemies[0].y;advance(.1);assert.ok(g.enemies[0].y>bossY,'Boss advances after volley');reset();assert.equal(g.hostile.length,0,'Restart clears projectiles');
console.log('PASS: ranged warnings, projectile travel/block/damage, pending-wave guard, pause, boss volley and advance.');

reset();g.remaining=0;g.hostile=[0,1,2].map(()=>({x:200,y:500,vx:0,vy:200}));advance(.04);assert.equal(g.hp,4,'Simultaneous volley counts as one hit');advance(.45);g.hostile=[{x:200,y:500,vx:0,vy:200}];advance(.04);assert.equal(g.hp,3,'Later attacks hurt after recovery');
const loadSave=effects.find(f=>f.toString().includes("getItem('runeblade-progress-v1')"));assert.ok(loadSave);
storage.set('runeblade-progress-v1',JSON.stringify({coins:123,sword:2,magic:1,shield:3,unlocked:2,equipped:1}));loadSave();assert.equal(api.progress.current.coins,123);assert.equal(api.progress.current.equipped,1);assert.equal(api.progress.current.shield,3,'Reload restores upgrades');
storage.set('runeblade-progress-v1',JSON.stringify({coins:42,sword:1,magic:0,shield:0}));loadSave();assert.equal(api.progress.current.coins,42);assert.equal(api.progress.current.equipped,0,'Old saves migrate');
storage.set('runeblade-progress-v1',JSON.stringify({coins:-5,sword:99,unlocked:0,equipped:2}));loadSave();assert.equal(api.progress.current.coins,0);assert.equal(api.progress.current.sword,0);assert.equal(api.progress.current.equipped,0,'Invalid values cannot unlock weapons');
const previous=api.progress.current;storage.set('runeblade-progress-v1','broken');loadSave();assert.equal(api.progress.current,previous,'Corrupt save does not crash or overwrite session progress');
console.log('PASS: damage recovery, saved reload, legacy save migration, invalid and corrupt saves.');
reset();g.mode='lost';api.progress.current={coins:600,sword:2,magic:3,shield:3};api.buyAdvanced('sword');assert.equal(api.progress.current.coins,600,'Advanced requires rank 3');api.buyAdvanced('magic');assert.equal(api.progress.current.coins,400);assert.equal(api.progress.current.piercing,true);api.buyAdvanced('magic');assert.equal(api.progress.current.coins,400,'No duplicate skill charge');loadSave();assert.equal(api.progress.current.piercing,true,'Advanced skill survives reload');
reset();api.progress.current={coins:0,sword:0,magic:0,shield:0,charged:true};g.remaining=99;g.spawn=100;g.enemies=[{x:200,y:450,hp:50,kind:'grunt',maxHp:50,speed:0,warning:.8,wind:-1,flash:0}];for(let i=0;i<4;i++){g.enemies[0].y=450;listeners.keydown({code:'Space',preventDefault(){},repeat:false});advance(.05);listeners.keyup({code:'Space'});advance(.3);}assert.equal(g.enemies[0].hp,40,'Fourth successful swing doubles damage');assert.equal(g.combo,0);
reset();api.progress.current={coins:0,sword:0,magic:0,shield:0,piercing:true};g.spawn=100;g.enemies=[450,380,310].map(y=>({x:200,y,hp:10,kind:'grunt',maxHp:10,speed:0,warning:.8,wind:-1,flash:0}));g.bolts=[{x:200,y:500}];advance(.5);assert.equal(g.enemies[0].hp,9.3);assert.equal(g.enemies[1].hp,9.3);assert.equal(g.enemies[2].hp,10,'Piercing stops after two unique enemies');
reset();api.progress.current={coins:0,sword:0,magic:0,shield:0,parry:true};g.spawn=100;g.enemies=[{x:200,y:400,hp:10,kind:'grunt',maxHp:10,speed:0,warning:.8,wind:-1,flash:0}];inputs.left.add(1);g.hostile=[{x:200,y:500,vx:0,vy:200}];advance(.04);assert.ok(g.enemies[0].stun>1);assert.equal(g.notice,'PERFECT GUARD');advance(1.3);assert.equal(g.enemies[0].stun,0,'Stun expires');g.hostile=[{x:200,y:500,vx:0,vy:200}];advance(.04);assert.equal(g.enemies[0].stun,0,'Holding shield does not repeatedly parry');
console.log('PASS: advanced purchase/reload, charged combo, two-target piercing, timed parry and stun expiry.');
reset();api.progress.current={coins:0,sword:0,magic:0,shield:0};g.wave=5;g.remaining=1;g.spawn=0;advance(.01);const realBoss=g.enemies[0];realBoss.y=420;realBoss.x=200;realBoss.casts=1;realBoss.speed=0;const originalHp=realBoss.hp;g.bolts=[{x:200,y:480}];advance(.1);assert.ok(realBoss.hp<originalHp,'Actual wave-five boss takes bolt damage');const afterBolt=realBoss.hp;listeners.keydown({code:'Space',preventDefault(){},repeat:false});advance(.05);listeners.keyup({code:'Space'});assert.equal(realBoss.hp,afterBolt-2,'Sword reaches visible lower edge of boss');
reset();g.spawn=999;advance(10);assert.equal(g.runSpeed,245,'Clear road accelerates to capped speed');const fullSpeed=g.runSpeed;g.enemies=[0,1,2].map(()=>({x:200,y:450,hp:100,kind:'grunt',maxHp:100,speed:0,warning:.8,wind:-1,flash:0,stun:100}));advance(2);assert.ok(g.runSpeed<fullSpeed,'Crowding slows running');assert.ok(g.runSpeed>=75);g.enemies=[];advance(6);assert.equal(g.runSpeed,245,'Clearing crowd restores speed');listeners.blur();const distance=g.distance,speed=g.runSpeed;advance(2);assert.equal(g.distance,distance);assert.equal(g.runSpeed,speed);reset();assert.equal(g.runSpeed,125);assert.equal(g.distance,0);
console.log('PASS: wave-five boss bolt and sword damage, acceleration cap, crowd slowdown, recovery, pause/reset.');
reset();api.progress.current={coins:10,sword:0,magic:0,shield:0,bestWave:3};g.wave=8;g.spawn=100;advance(.01);assert.equal(api.progress.current.bestWave,8);assert.equal(JSON.parse(storage.get('runeblade-progress-v1')).bestWave,8);reset();advance(.01);assert.equal(api.progress.current.bestWave,8,'Lower run preserves record');loadSave();assert.equal(api.progress.current.bestWave,8,'Best wave survives reload');
reset();api.progress.current={coins:0,sword:0,magic:0,shield:0,charged:true};g.combo=3;g.enemies=[{x:200,y:450,hp:10,kind:'grunt',maxHp:10,speed:0,warning:.8,wind:-1,flash:0}];listeners.keydown({code:'Space',preventDefault(){},repeat:false});advance(.05);listeners.keyup({code:'Space'});assert.ok(g.chargedFx>0);assert.equal(g.enemies[0].hp,6);listeners.blur();const effect=g.chargedFx;advance(1);assert.equal(g.chargedFx,effect,'Pause freezes feedback effect');reset();assert.equal(g.chargedFx,0);assert.equal(g.parryFx,0);
console.log('PASS: best wave persistence and charged feedback lifecycle.');

reset();assert.equal(g.loot.length,0,'Restart clears dropped coins');g.spawn=100;g.enemies=[{x:200,y:200,hp:0,kind:'grunt',maxHp:3,speed:0,warning:.8,wind:-1,flash:0}];advance(.32);assert.equal(g.loot.length,2);assert.ok(g.loot[0].z>10,'Coins launch into the air');advance(.6);assert.ok(g.loot[0].z<10,'Coins land and bounce');g.hp=0;advance(.01);const lostCoins=g.coins;advance(4);assert.equal(g.coins,lostCoins,'Death stops collection');console.log('PASS: bouncing loot, deferred credit, pause, pickup persistence, no duplicate rewards, death and restart.');

reset();g.spawn=100;api.progress.current={coins:0,sword:0,magic:0,shield:0};
for(const key of ['frenzy','storm','guard','magnet','frost','flame','chain','guardian'])api.collectPower(key);
assert.equal(Object.keys(g.buffs).length,8,'Different powers stack');advance(1);api.collectPower('frenzy');assert.equal(g.buffs.frenzy,8,'Duplicate refreshes duration');
g.mode='paused';const frozen=JSON.stringify(g.buffs);advance(1);assert.equal(JSON.stringify(g.buffs),frozen,'Pause freezes power timers');g.mode='playing';
g.hp=4;api.collectPower('heal');assert.equal(g.hp,5);api.collectPower('heal');assert.equal(g.hp,5,'Healing capped');assert.equal(g.buffs.heal,undefined);
g.hp=1;g.hurt=0;api.takeHit(2);assert.equal(g.hp,1);assert.equal(g.buffs.guardian,undefined,'Guardian consumed once');assert.ok(g.hurt>1);g.hurt=0;api.takeHit(1);assert.equal(g.hp,0,'Second fatal hit is not prevented');
reset();g.spawn=100;api.collectPower('storm');inputs.right.set(9,now-300);advance(.01);assert.equal(g.bolts.length,3,'Storm fires three bolts');assert.equal(new Set(g.bolts.map(b=>b.vx)).size,3);inputs.right.clear();
reset();g.spawn=100;g.stamina=10;api.collectPower('guard');inputs.left.add(1);g.hostile=[{x:200,y:504,vx:0,vy:200}];advance(.02);assert.equal(g.hp,5);assert.equal(g.stamina,10,'Guard has no drain or impact cost');
reset();g.spawn=100;api.collectPower('frenzy');api.collectPower('flame');g.enemies=[{x:200,y:410,hp:20,kind:'grunt',maxHp:20,speed:0,warning:.8,wind:-1,flash:0}];api.swing();assert.equal(g.enemies[0].hp,18,'Frenzy reaches farther');assert.equal(g.cooldown,.16);advance(.2);assert.ok(g.enemies[0].hp<18,'Flame burns after swing');
reset();g.spawn=100;api.collectPower('chain');g.enemies=[450,350,250].map(y=>({x:200,y,hp:10,kind:'grunt',maxHp:10,speed:0,warning:.8,wind:-1,flash:0}));g.bolts=[{x:200,y:460}];advance(.01);assert.ok(g.enemies.every(e=>e.hp<10),'Lightning jumps twice');assert.equal(g.arcs.length,2);
reset();g.spawn=100;api.collectPower('frost');g.hostile=[{x:200,y:400,vx:0,vy:200}];advance(.1);assert.ok(Math.abs(g.hostile[0].y-410)<.01,'Frost halves nearby projectile speed');advance(6);assert.equal(g.buffs.frost,undefined,'Powers expire');
reset();g.spawn=100;api.collectPower('magnet');g.loot=[{x:150,y:250,z:0,vz:0,vx:0,age:0,value:2}];advance(.7);assert.equal(g.loot.length,0,'Magnet collects distant coins sooner');
reset();g.spawn=100;g.enemies=[{x:200,y:100,hp:0,kind:'boss',maxHp:30,speed:0,warning:1,wind:-1,flash:0}];advance(.01);assert.equal(g.drops.length,1,'Boss guarantees a drop');advance(.3);assert.ok(g.drops[0].z>12,'Power pickup bounces');g.mode='paused';const dropState=JSON.stringify(g.drops);advance(1);assert.equal(JSON.stringify(g.drops),dropState);g.mode='playing';advance(3);assert.equal(g.drops.length,0,'Hero collects power pickup');reset();assert.equal(Object.keys(g.buffs).length,0);assert.equal(g.drops.length,0);assert.equal(g.arcs.length,0);
console.log('PASS: all nine powers, stacking, refresh, pause, expiry, guardian, drops and reset.');

reset();g.spawn=100;api.collectPower('flame',180,520);assert.equal(g.celebrations.length,1);assert.equal(g.celebrations[0].x,180);g.mode='paused';advance(1);assert.equal(g.celebrations[0].age,0);g.mode='playing';advance(1.6);assert.equal(g.celebrations.length,0);g.buffs.flame=.01;advance(.02);assert.ok(g.powerFades.flame>0,'Expired visual fades out');advance(.5);assert.equal(g.powerFades.flame,undefined);api.collectPower('heal');reset();assert.equal(g.celebrations.length,0);assert.equal(Object.keys(g.powerFades).length,0);console.log('PASS: pickup celebration, pause, expiry fade and restart.');

reset();g.spawn=100;api.progress.current={coins:0,sword:0,magic:0,shield:0};
g.enemies=['grunt','brute','boss'].map(kind=>({x:200,y:465,hp:20,kind,maxHp:20,speed:0,warning:1,wind:.1,flash:0}));api.swing();assert.ok(g.enemies.every(e=>e.recoil>0&&e.wind===-1),'Surviving sword targets recoil and cancel windup');advance(.1);assert.ok(g.enemies[0].y<g.enemies[1].y&&g.enemies[1].y<g.enemies[2].y,'Heavy foes resist knockback');const recoilY=g.enemies[0].y;g.mode='paused';advance(1);assert.equal(g.enemies[0].y,recoilY,'Pause freezes knockback');g.mode='playing';advance(.2);assert.equal(g.enemies[0].recoil,0,'Recoil ends');
reset();g.spawn=100;g.enemies=[{x:200,y:465,hp:1,kind:'grunt',maxHp:3,speed:0,warning:1,wind:-1,flash:0}];api.swing();assert.ok(g.enemies[0].hp<=0);assert.equal(g.enemies[0].recoil,undefined,'Lethal sword hit has no knockback');
reset();g.spawn=100;g.enemies=[{x:200,y:450,hp:10,kind:'grunt',maxHp:10,speed:0,warning:1,wind:-1,flash:0}];g.bolts=[{x:200,y:460}];advance(.01);assert.equal(g.enemies[0].recoil,undefined,'Magic does not cause sword knockback');console.log('PASS: nonlethal sword knockback, weight resistance, pause, recovery and lethal/magic exclusions.');

reset();g.spawn=100;g.enemies=[{x:200,y:335,hp:20,kind:'runner',maxHp:20,speed:100,warning:.55,wind:-1,flash:0}];advance(.2);assert.equal(g.enemies[0].y,335,'Runner telegraphs before charging');advance(.6);assert.ok(g.enemies[0].y>335,'Runner charges after warning');
for(const [wave,type] of [[5,'knight'],[10,'golem'],[15,'wisp'],[20,'knight']]){reset();g.wave=wave;g.remaining=1;g.spawn=0;advance(.01);assert.equal(g.enemies[0].bossType,type,'Boss rotation');g.enemies[0].y=280;advance(1.2);if(type==='golem')assert.equal(g.hostile.length,0,'Golem closes in without firing');else assert.ok(g.hostile.length>0,'Ranged boss fires');}
console.log('PASS: runner warning/charge and rotating boss patterns.');

reset();g.spawn=100;g.enemies=[{x:200,y:200,hp:0,kind:'grunt',maxHp:3,speed:0,warning:1,wind:-1,flash:0}];advance(.01);assert.equal(g.defeats.length,1);assert.ok(g.loot[0].age<0,'Loot waits for defeat animation');g.mode='paused';const defeatAge=g.defeats[0].age;advance(1);assert.equal(g.defeats[0].age,defeatAge);g.mode='playing';advance(.6);assert.equal(g.defeats.length,0);reset();assert.equal(g.defeats.length,0);console.log('PASS: delayed reward appearance and defeat lifecycle.');

const gearLib=equipmentModule.exports;assert.equal(gearLib.catalog.sword.length,22);assert.equal(gearLib.catalog.magic.length,20);assert.equal(gearLib.catalog.shield.length,21);
reset();g.mode='lost';api.progress.current={coins:1000000,sword:0,magic:0,shield:0,unlocked:2,equipped:2};assert.equal(api.equipment().sword[2],0,'Legacy owned swords migrate');api.gearAction('sword',3,false);assert.equal(api.progress.current.equipped,3);const swordBase=api.damage('sword');api.gearAction('sword',3,true);assert.ok(api.damage('sword')>swordBase);const wallet=api.progress.current.coins;api.gearAction('magic',2,false);assert.equal(api.progress.current.coins,wallet,'No skipping unlocks');api.gearAction('magic',1,false);assert.equal(api.equipment().magicEquipped,1);api.gearAction('shield',1,false);api.gearAction('shield',1,true);loadSave();assert.equal(api.equipment().shield[1],1,'Individual ranks persist');assert.equal(api.equipment().magicEquipped,1,'Magic selection persists');for(let i=0;i<12;i++)api.gearAction('shield',1,true);assert.equal(api.equipment().shield[1],10,'Per-item rank cap');const cappedWallet=api.progress.current.coins;api.gearAction('shield',1,true);assert.equal(api.progress.current.coins,cappedWallet);
reset();g.spawn=100;api.progress.current={coins:1000,sword:0,magic:0,shield:0};const beforeMidrun=api.progress.current.coins;api.gearAction('magic',1,false);assert.equal(api.progress.current.coins,beforeMidrun,'No midrun purchases');g.enemies=[100,250,440].map(y=>({x:200,y,hp:20,kind:'grunt',maxHp:20,speed:0,warning:1,wind:-1,flash:0}));api.throwShield();assert.ok(g.flying);const wait=g.throwWait;api.throwShield();assert.equal(g.throwWait,wait,'Cannot spam throw');g.mode='paused';advance(1);assert.equal(g.throwWait,wait);assert.equal(g.flying.y,520);g.mode='playing';advance(1.5);assert.ok(g.enemies.every(e=>e.hp===18.5),'Shield hits all captured on-screen targets exactly once');assert.equal(g.flying,null,'Shield returns');reset();assert.equal(g.flying,null);assert.equal(g.throwWait,0);
for(const [index,effect] of [[1,'burn'],[2,'chill']]){reset();g.spawn=100;api.progress.current={coins:0,sword:0,magic:0,shield:0,gear:gearLib.gearDefaults()};for(let i=0;i<=index;i++)api.progress.current.gear.magic[i]=0;api.progress.current.gear.magicEquipped=index;g.enemies=[{x:200,y:450,hp:20,kind:'grunt',maxHp:20,speed:0,warning:1,wind:-1,flash:0}];g.bolts=[{x:200,y:460}];advance(.01);assert.ok(g.enemies[0][effect]>0,'Magic family applies its effect');}
console.log('PASS: 61-item catalogue, per-item ranks, migration, transactions, magic effects, shield ricochet and lifecycle.');

reset();g.mode='lost';api.progress.current={coins:1000000,sword:3,magic:3,shield:3};api.buySkill('tempo');assert.equal(api.skill('tempo'),0,'Prerequisite enforced');const baseDamage=api.damage('sword');for(let i=0;i<3;i++)api.buySkill('edge');assert.equal(api.skill('edge'),3);assert.ok(api.damage('sword')>baseDamage);api.buySkill('tempo');assert.equal(api.skill('tempo'),1);loadSave();assert.equal(api.skill('tempo'),1,'Skill ranks survive reload');for(let i=0;i<15;i++)api.buySkill('edge');assert.equal(api.skill('edge'),10);const treeCoins=api.progress.current.coins;api.buySkill('edge');api.buySkill('not-a-skill');assert.equal(api.progress.current.coins,treeCoins);reset();api.buySkill('tempo');assert.equal(api.skill('tempo'),1,'No midrun skill purchases');
api.progress.current={coins:0,sword:0,magic:0,shield:0,skills:{duration:10,renew:10,return:10,impact:10}};g.spawn=100;api.collectPower('frost');assert.equal(g.buffs.frost,7.800000000000001);g.stamina=0;advance(.1);assert.ok(g.stamina>2.8,'Regen skill affects combat');g.enemies=[{x:200,y:200,hp:100,kind:'grunt',maxHp:100,speed:0,warning:1,wind:-1,flash:0}];api.throwShield();assert.ok(g.throwWait<6);assert.ok(g.flying.damage>2);const invalid=skillsModule.exports.loadSkills({edge:99,tempo:8,renew:-1},{sword:3,magic:3,shield:3});assert.equal(invalid.tempo,undefined,'Invalid saves cannot bypass prerequisites');console.log('PASS: expanded skill prerequisites, rank caps, saves, purchase guards and combat bonuses.');

reset();g.mode='lost';api.progress.current={coins:1000000,sword:3,magic:3,shield:3,charged:true,piercing:true,parry:true};for(const branch of ['sword','magic','shield'])for(let i=0;i<27;i++)api.buy(branch);assert.equal(api.progress.current.sword,30);assert.equal(api.progress.current.magic,30);assert.equal(api.progress.current.shield,30);const masteryWallet=api.progress.current.coins;api.buy('shield');assert.equal(api.progress.current.coins,masteryWallet,'Mastery cap prevents extra spending');loadSave();assert.equal(api.progress.current.shield,30,'High mastery survives reload');assert.equal(api.progress.current.charged,true);assert.equal(api.progress.current.piercing,true);assert.equal(api.progress.current.parry,true,'Advanced abilities survive high mastery reload');reset();g.spawn=100;inputs.left.add(1);advance(1);assert.ok(g.stamina<100&&g.stamina>94,'Rank 30 drain stays positive and improves endurance');console.log('PASS: 30 mastery ranks, saved advanced abilities, rank cap and positive shield drain.');

for(let region=0;region<10;region++){reset();g.wave=region*5+1;g.remaining=1;g.spawn=0;advance(.01);assert.equal(g.enemies[0].region,region,'Every region spawns its matching faction');}reset();g.wave=50;g.remaining=0;advance(.01);assert.ok(g.notice.includes('VEYR FALLS'));advance(3.1);assert.equal(g.wave,51);advance(1);assert.equal(g.enemies[0].region,0,'New cycle starts at first region');console.log('PASS: ten regions, wave-50 milestone and endless cycle transition.');

reset();g.mode='lost';api.progress.current={coins:1000000,sword:0,magic:0,shield:0};api.gearAction('sword',21,false);assert.equal(api.equipment().sword[21],-1,'Infinity cannot be bought');for(const wave of [5,15,25,35])api.recoverRelic(wave);assert.equal(api.equipment().sword[21],-1);api.recoverRelic(45);assert.equal(api.equipment().sword[21],0,'Five relics forge Infinity');assert.equal(api.progress.current.relics.length,5);api.recoverRelic(45);assert.equal(api.progress.current.relics.length,5,'No duplicate relics');api.gearAction('sword',21,false);assert.equal(api.progress.current.equipped,21);loadSave();assert.equal(api.progress.current.equipped,21,'Infinity persists despite earlier locked swords');assert.equal(api.progress.current.relics.length,5);assert.ok(api.damage('sword')>gearLib.catalog.sword[20].damage);reset();g.wave=50;g.remaining=1;g.spawn=0;advance(.01);assert.equal(g.enemies[0].finalBoss,true);g.enemies[0].hp=0;advance(.01);assert.equal(api.progress.current.storyComplete,true);loadSave();assert.equal(api.progress.current.storyComplete,true);console.log('PASS: relic persistence, exclusive Infinity unlock/equip and final villain story completion.');

reset();g.spawn=100;api.progress.current={coins:0,sword:0,magic:0,shield:0};api.lunge();assert.equal(g.lungeWait,0);
g.enemies=[100,250,440].map(y=>({x:200,y,hp:100,kind:'grunt',maxHp:100,speed:0,warning:1,wind:-1,flash:0}));
api.lunge();assert.ok(g.lunge);const lungeDamage=g.lunge.damage;assert.equal(lungeDamage,api.damage('sword')*1.5);api.lunge();assert.equal(g.lungeWait,10);api.takeHit(2);assert.equal(g.hp,5);api.swing();assert.equal(g.slash,0);
g.mode='paused';advance(.5);assert.equal(g.lunge.y,535);assert.equal(g.lungeWait,10);g.mode='playing';advance(2);assert.equal(g.lunge,null);assert.ok(g.enemies.every(e=>e.hp===100-lungeDamage),'Lunge hits each target once');assert.ok(g.lungeWait>0);
reset();assert.equal(g.lunge,null);assert.equal(g.lungeWait,0);assert.equal(g.dashTrail.length,0);
console.log('PASS: lunge targets, sword scaling, cooldown, immunity, pause and reset.');

assert.equal(gearLib.catalog.shield[20].name,"Captain America Shield");assert.ok(gearLib.gearDamage("shield",20,0)>gearLib.gearDamage("shield",19,0));assert.equal(gearLib.loadGear({shield:Array(20).fill(2)},0).shield[20],-1,"Old saves keep final shield locked");

reset();g.mode='lost';api.progress.current={coins:0,sword:0,magic:0,shield:0};api.itemAction('titan');assert.equal(api.progress.current.items,undefined,'Cannot buy without coins');api.progress.current.coins=200000;
for(const id of ['titan','storm','time','winter','phoenix','aegis'])api.itemAction(id);
assert.equal(api.progress.current.loadout.length,3);assert.equal(api.progress.current.items.length,6);api.itemAction('winter');assert.equal(api.hasItem('winter'),false,'Fourth item cannot equip');assert.equal(api.damage('sword'),4);api.itemAction('titan');api.itemAction('phoenix');loadSave();assert.equal(api.hasItem('phoenix'),true,'Loadout survives reload');assert.equal(api.progress.current.loadout.length,3);
reset();g.spawn=100;const beforeItems=JSON.stringify(api.progress.current);api.itemAction('storm');assert.equal(JSON.stringify(api.progress.current),beforeItems,'No midrun loadout changes');g.hp=1;api.takeHit(2);assert.equal(g.hp,5);assert.equal(g.revived,true);assert.equal(g.hurt,3);g.hurt=0;g.hp=1;api.takeHit(2);assert.ok(g.hp<=0,'Phoenix only once');reset();assert.equal(g.revived,false);
g.enemies=[{x:200,y:200,hp:100,kind:'grunt',maxHp:100,speed:0,warning:1,wind:-1,flash:0}];api.lunge();assert.equal(g.lungeWait,5,'Hourglass halves cooldown');
reset();g.spawn=100;inputs.right.set(1,now-300);advance(.01);assert.equal(g.bolts.length,3,'Crown fires triple bolts');inputs.right.clear();
console.log('PASS: legendary purchases, three slots, saved loadouts, damage, resurrection, cooldown and triple casting.');

reset();g.mode='lost';api.progress.current={coins:1000000,sword:0,magic:0,shield:0};for(const id of ['archmage','berserker','void','dragon','everlasting','sentinel'])api.itemAction(id);assert.equal(api.progress.current.items.length,6);assert.equal(api.progress.current.loadout.length,3);assert.equal(api.damage('magic'),1.4);
api.itemAction('archmage');api.itemAction('void');api.itemAction('dragon');api.itemAction('everlasting');loadSave();reset();g.spawn=100;api.collectPower('frost');assert.equal(g.buffs.frost,12);g.enemies=[{x:200,y:460,hp:100,kind:'grunt',maxHp:100,speed:0,warning:1,wind:-1,flash:0}];api.swing();assert.equal(g.enemies[0].burn,6);assert.equal(g.enemies[0].knockback,840);assert.ok(g.cooldown<.18);
g.mode='lost';api.itemAction('berserker');api.itemAction('sentinel');reset();g.spawn=100;g.stamina=0;advance(.1);assert.ok(g.stamina>5,'Heartstone triple regeneration');console.log('PASS: new legendary ownership, slots, persistence, magic, power duration, burning, knockback and regeneration.');

reset();g.mode='lost';api.progress.current={coins:1000000,sword:0,magic:0,shield:0};for(const id of ['midas','comet','reaper','magnetar','duelist','glacier','bulwark','oracle'])api.itemAction(id);assert.equal(api.progress.current.items.length,8);assert.equal(api.progress.current.loadout.length,3);loadSave();assert.equal(api.progress.current.items.length,8);
reset();g.spawn=100;g.loot=[{x:200,y:526,z:0,vz:0,vx:0,age:1,value:5}];advance(.01);assert.equal(g.coins,10);inputs.right.set(1,now-300);advance(.01);assert.ok(g.shot<=.12);inputs.right.clear();g.enemies=[{x:200,y:460,hp:20,kind:'grunt',maxHp:100,speed:0,warning:1,wind:-1,flash:0}];api.swing();assert.equal(g.enemies[0].hp,14);
g.mode='lost';api.itemAction('midas');api.itemAction('duelist');reset();g.spawn=100;g.enemies=[{x:200,y:200,hp:100,kind:'grunt',maxHp:100,speed:0,warning:1,wind:-1,flash:0}];api.lunge();assert.equal(g.lunge.damage,api.damage('sword')*4.5);console.log('PASS: eight new items, loadout persistence, double coins, rapid casting, execution and lunge damage.');
